config/routes.rb
Rails.application.routes.draw do
  if Settings.service.admin || Settings.service.sidekiq
    scope :admin do
      devise_for :admin_users, ActiveAdmin::Devise.config
    end
  end

  ActiveAdmin.routes(self) if Settings.service.admin

  authenticate :admin_user do
    if Settings.service.sidekiq
      require 'sidekiq/web'
      mount Sidekiq::Web => '/admin/sidekiq_web'
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    invitations: 'users/invitations'
  }

  resources :tests, shallow: true do
    resources :user_tests, only: [:create, :update, :index, :destroy]
    resources :test_versions, only: [] do
      resources :user_test_versions, only: [:create, :update, :index, :destroy]
    end
    resources :user_notification_settings, only: [:index], path: :notification_settings
  end
  resources :user_integrations, only: [:index] do
    collection do
      resources :slack_integrations, path: 'slack'
    end
    resources :user_notification_settings, only: [:index], path: :notification_settings
  end
  get 'user_integrations/:type/:id', to: -> { root_path }, as: :polymorphic_user_integration # Fake route for polymorphic routes
  resources :tests, only: [] do
    get 'versions' => 'test_versions#index', as: :test_versions
    get ':number' => 'test_versions#show', as: :test_version
    delete ':number' => 'test_versions#destroy'
    nested do
      scope ':number', as: :version do
        resources :test_executions, only: [:index, :create]
      end
    end
  end
  resources :test_executions, shallow: true, only: [:show] do
    member do
      get :done
    end
    resources :test_execution_shares, only: [:index, :create, :update, :destroy]
  end
  resources :test_step_executions, only: [:show]
  resources :user_credentials, only: [:index] do
    collection do
      resource :browserstack_credentials, only: [:create, :update, :destroy], path: :browserstack
    end
  end
  resources :test_step_sets, shallow: true do
    resources :user_shared_test_step_sets, only: [:index, :create, :destroy]
  end
  resources :user_api_tokens, path: 'api_tokens', only: [:index, :create, :update, :destroy]
  namespace :misc, path: '' do
    get :assigned_tests
    get :test_executions
  end
  resources :user_notification_settings, only: [:index, :create, :update], path: :notification_settings
  namespace :docs do
    get :api
  end

  namespace :api, constraints: { format: 'json' }, defaults: { format: 'json' } do
    namespace :v1 do
      resources :tests, only: [] do
        get 'versions' => 'test_versions#index', as: :test_versions
        get ':number' => 'test_versions#show', as: :test_version
        delete ':number' => 'test_versions#destroy'
        nested do
          scope ':number', as: :version do
            resources :test_executions, only: [:index, :create]
          end
        end
      end
      resources :test_executions, only: [:show]
      get :docs, to: 'docs#index'
    end
    namespace :graphql do
      resource :query, only: [:create, :show]
      resource :schema, only: [:show]
    end
    match '*path' => 'misc#not_found', via: :all
  end

  root to: 'misc#home'
end

app/controllers/slack_integrations_controller.rb
class SlackIntegrationsController < BaseController
  def show
    @integration = UserIntegration::Slack.find(params[:id])
    authorize @integration
  end

  def new
    @integration = current_user.user_integrations.build.becomes! UserIntegration::Slack
    authorize @integration
  end

  def create
    @integration = current_user.user_integrations.build.becomes! UserIntegration::Slack
    authorize @integration

    @integration.assign_attributes(permitted_params)

    if @integration.save
      flash[:notice] = t('shared.create_success', target: UserIntegration::Slack.model_name.human)
      redirect_to origin || slack_integration_path(@integration)
      return
    end

    render :new
  end

  def edit
    @integration = UserIntegration::Slack.find(params[:id])
    authorize @integration
  end

  def update
    @integration = UserIntegration::Slack.find(params[:id])
    authorize @integration

    @integration.assign_attributes(permitted_params)

    if @integration.save
      flash[:notice] = t('shared.update_success', target: UserIntegration::Slack.model_name.human)
      redirect_to origin || slack_integration_path(@integration)
      return
    end

    render :edit
  end

  def destroy
    @integration = UserIntegration::Slack.find(params[:id])
    authorize @integration

    @integration.destroy!

    flash[:notice] = t('shared.destroy_success', target: UserIntegration::Slack.model_name.human)
    redirect_to origin || user_integrations_path
  end

  private

  def permitted_params
    params.require(:integration).permit(:name, :webhook_url)
  end
end

app/views/slack_integrations/_form.html.slim
= f.error_notification
= f.input :name
= f.input :webhook_url
= f.button :submit, class: 'btn-success'

app/views/slack_integrations/edit.html.slim
= link_to t('shared.back_link', target: UserIntegration::Base.model_name.human(count: 2)), user_integrations_path

h1
  = image_tag image_path("integrations/slack.png"), width: 32, height: 32
  = " #{t('.title')}"

= simple_form_for @integration, url: slack_integration_path(@integration), as: :integration, method: :put do |f|
  = render 'form', f: f

app/views/slack_integrations/new.html.slim
= link_to t('shared.back_link', target: UserIntegration::Base.model_name.human(count: 2)), user_integrations_path

h1
  = image_tag image_path("integrations/slack.png"), width: 32, height: 32
  = " #{t('.title')}"

= simple_form_for @integration, url: slack_integrations_path, as: :integration, method: :post do |f|
  = render 'form', f: f

app/views/slack_integrations/show.html.slim
= link_to t('shared.back_link', target: UserIntegration::Base.model_name.human(count: 2)), user_integrations_path

h1
  = image_tag image_path("integrations/slack.png"), width: 32, height: 32
  = " #{UserIntegration::Slack.model_name.human.humanize}"

.block
  .pull-right
    .e2e-margined-btn-group
      - if policy(@integration).edit?
        = link_to t('shared.buttons.edit'), edit_slack_integration_path(@integration), class: 'btn btn-default'
      - if policy(@integration).destroy?
        = link_to t('shared.buttons.delete'), slack_integration_path(@integration), method: :delete, data: { confirm: t('shared.confirm') }, class: 'btn btn-default'
      = link_to t('shared.buttons.settings'), user_integration_user_notification_settings_path(@integration), class: 'btn btn-default'
  h2.e2e-truncate
    = @integration.name

.block
  .row
    .col-lg-3.text-right
      = UserIntegration::Slack.human_attribute_name(:webhook_url).humanize
    .col-lg-9
      = @integration.webhook_url
  - if @integration.last_error.present?
    .row.text-danger
      .col-lg-3.text-right
        .glyphicon.glyphicon-exclamation-sign
        = UserIntegration::Slack.human_attribute_name(:last_error).humanize
      .col-lg-9
        code = @integration.last_error