config/routes.rb
Rails.application.routes.draw do
  if Settings.service.admin || Settings.service.sidekiq
    scope :admin do
      devise_for :admin_users, ActiveAdmin::Devise.config
    end
  end

  ActiveAdmin.routes(self) if Settings.service.admin

  authenticate :admin_user do
    if Settings.service.sidekiq
      require 'sidekiq/web'
      mount Sidekiq::Web => '/admin/sidekiq_web'
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    invitations: 'users/invitations'
  }

  resources :tests, shallow: true do
    resources :user_tests, only: [:create, :update, :index, :destroy]
    resources :test_versions, only: [] do
      resources :user_test_versions, only: [:create, :update, :index, :destroy]
    end
    resources :user_notification_settings, only: [:index], path: :notification_settings
  end
  resources :user_integrations, only: [:index] do
    collection do
      resources :slack_integrations, path: 'slack'
    end
    resources :user_notification_settings, only: [:index], path: :notification_settings
  end
  get 'user_integrations/:type/:id', to: -> { root_path }, as: :polymorphic_user_integration # Fake route for polymorphic routes
  resources :tests, only: [] do
    get 'versions' => 'test_versions#index', as: :test_versions
    get ':number' => 'test_versions#show', as: :test_version
    delete ':number' => 'test_versions#destroy'
    nested do
      scope ':number', as: :version do
        resources :test_executions, only: [:index, :create]
      end
    end
  end
  resources :test_executions, shallow: true, only: [:show] do
    member do
      get :done
    end
    resources :test_execution_shares, only: [:index, :create, :update, :destroy]
  end
  resources :test_step_executions, only: [:show]
  resources :user_credentials, only: [:index] do
    collection do
      resource :browserstack_credentials, only: [:create, :update, :destroy], path: :browserstack
    end
  end
  resources :test_step_sets, shallow: true do
    resources :user_shared_test_step_sets, only: [:index, :create, :destroy]
  end
  resources :user_api_tokens, path: 'api_tokens', only: [:index, :create, :update, :destroy]
  namespace :misc, path: '' do
    get :assigned_tests
    get :test_executions
  end
  resources :user_notification_settings, only: [:index, :create, :update], path: :notification_settings
  namespace :docs do
    get :api
  end

  namespace :api, constraints: { format: 'json' }, defaults: { format: 'json' } do
    namespace :v1 do
      resources :tests, only: [] do
        get 'versions' => 'test_versions#index', as: :test_versions
        get ':number' => 'test_versions#show', as: :test_version
        delete ':number' => 'test_versions#destroy'
        nested do
          scope ':number', as: :version do
            resources :test_executions, only: [:index, :create]
          end
        end
      end
      resources :test_executions, only: [:show]
      get :docs, to: 'docs#index'
    end
    namespace :graphql do
      resource :query, only: [:create, :show]
      resource :schema, only: [:show]
    end
    match '*path' => 'misc#not_found', via: :all
  end

  root to: 'misc#home'
end

app/models/test_step_set.rb
class TestStepSet < ApplicationRecord
  belongs_to :user, inverse_of: :test_step_sets
  belongs_to :base_test_step_set, class_name: 'TestStepSet', foreign_key: 'base_test_step_set_id', inverse_of: :inherited_test_step_sets
  has_many :inherited_test_step_sets, class_name: 'TestStepSet', foreign_key: 'base_test_step_set_id', inverse_of: :base_test_step_set
  has_many :test_steps, -> { order(position: :asc) }, class_name: 'TestStep::Base', inverse_of: :test_step_set
  has_many :test_step_sets, class_name: 'TestStep::StepSet', inverse_of: :shared_test_step_set
  has_many :shared_test_step_sets, through: :test_step_sets, source: :shared_test_step_set

  validates :user, presence: true
  validates :title, length: { minimum: 1, maximum: 100 }, presence: true
  validates :description, length: { maximum: 65_535 }, allow_blank: true
  validates :test_steps, length: { minimum: 1, maximum: 50 }, allow_blank: true

  acts_as_paranoid

  accepts_nested_attributes_for :test_steps, allow_destroy: true

  def same_test_step_set?(other)
    return false if other.nil?
    return false if self.class != other.class
    return false if test_steps.length != other.test_steps.length
    return false if test_steps.map { |ts| ts.becomes ts.type.constantize }.zip(other.test_steps.map { |ts| ts.becomes ts.type.constantize }).any? { |a, b| !a.same_step?(b) }
    return false if title != other.title
    return false if description != other.description
    base_test_step_set_id == other.base_test_step_set_id ||
      base_test_step_set_id == other.id ||
      other.base_test_step_set_id == id
  end
end

app/controllers/test_step_sets_controller.rb
class TestStepSetsController < BaseController
  auto_decorate :test_step_sets, :test_step_set, only: [:index, :show]

  def index
    @test_step_sets = policy_scope(current_user.accessible_shared_test_step_sets).latest.page(params[:page]).per(20)
  end

  def show
    @test_step_set = SharedTestStepSet.find(params[:id])
    authorize @test_step_set

    @user_shared_test_step_sets = @test_step_set.user_shared_test_step_sets.limit(10)
  end

  def new
    @base_test_step_set = (params[:base_test_step_set_id].presence && TestStepSet.find(params[:base_test_step_set_id]))
    authorize @base_test_step_set, :show? if @base_test_step_set.present?

    @test_step_set = current_user.shared_test_step_sets.build
    authorize @test_step_set

    @base_test_step_set ||= @test_step_set
  end

  def create
    @base_test_step_set = (params[:base_test_step_set_id].presence && TestStepSet.find(params[:base_test_step_set_id]))
    authorize @base_test_step_set, :show? if @base_test_step_set.present?

    @test_step_set = current_user.shared_test_step_sets.build(permitted_create_params.merge(user: current_user, base_test_step_set: @base_test_step_set))
    authorize @test_step_set

    if @test_step_set.save
      flash[:notice] = t('shared.create_success', target: SharedTestStepSet.model_name.human)
      return redirect_to test_step_set_path(@test_step_set)
    end

    @base_test_step_set = @test_step_set
    render :new
  end

  def edit
    @test_step_set = SharedTestStepSet.find(params[:id])
    authorize @test_step_set
  end

  def update
    @test_step_set = SharedTestStepSet.find(params[:id])
    authorize @test_step_set

    if @test_step_set.update_attributes(permitted_update_params)
      flash[:notice] = t('shared.update_success', target: SharedTestStepSet.model_name.human)
      redirect_to test_step_set_path(@test_step_set)
      return
    end

    render :edit
  end

  def destroy
    @test_step_set = SharedTestStepSet.find(params[:id])
    authorize @test_step_set

    @test_step_set.destroy!

    flash[:notice] = t('shared.destroy_success', target: SharedTestStepSet.model_name.human)
    redirect_to test_step_sets_path
  end

  private

  def permitted_create_params
    params.require(:test_step_set).permit(
      :title,
      :description,
      test_steps_attributes:
        [:test_step_type, :_destroy, data: [:message, :selector, :javascript, :value, :url, :width, :height, :shared_test_step_set_id, :duration]]
    )
  end

  def permitted_update_params
    params.require(:test_step_set).permit(:title, :description)
  end
end

app/views/test_step_sets/edit.html.slim
- content_for :title, t('.title', test_step_set_title: @test_step_set.title).titleize

= link_to t('shared.back_link', target: SharedTestStepSet.model_name.human), test_step_set_path(@test_step_set)

h1 = t('.title', test_step_set_title: @test_step_set.title)

= simple_form_for @test_step_set, url: test_step_set_path(@test_step_set), method: :put, as: :test_step_set do |f|
  = f.error_notification
  = f.input :title
  = f.input :description, hint: t('shared.markdown_support_hint', link: link_to(t('shared.what_is_markdown'), doc_url(:markdown), target: '_blank')).html_safe
  = f.button :submit, class: 'btn-success'

app/views/test_step_sets/index.html.slim
.block
  .pull-right
    = link_to t('shared.buttons.new', target: SharedTestStepSet.model_name.human), new_test_step_set_path, class: 'btn btn-success'

  h1
    small.glyphicon.glyphicon-share
    = " #{t('.title')}"

- if @test_step_sets.present?
  .panel.panel-default
    table.table.table-striped
      tr
        th = SharedTestStepSet.human_attribute_name(:base_test_step_set)
        th = SharedTestStepSet.human_attribute_name(:title)
        th = SharedTestStepSet.human_attribute_name(:created_at)
        th = SharedTestStepSet.human_attribute_name(:user)
        th
      - @test_step_sets.each do |tv|
        tr
          td = link_to tv.base_test_step_set.title, polymorphic_test_step_set_path(tv.base_test_step_set) if tv.base_test_step_set.present? && policy(tv.base_test_step_set).show?
          td = link_to tv.title, test_step_set_path(tv)
          td = link_to test_step_set_path(tv) do
            time datetime=tv.created_at.iso8601 data-timeago='' = tv.created_at.to_s
          td
            = gravatar_image_tag(tv.user.email, alt: tv.user.name, gravatar: { size: 20 })
            |  
            = tv.user.name
          td
            = link_to t('shared.buttons.create_test'), new_test_path(base_test_step_set_id: tv), class: 'btn btn-xs btn-success'
  .center-block.text-center
    = paginate @test_step_sets
-else
  .alert.alert-warning
    = t('shared.no_records', target: SharedTestStepSet.model_name.human)

app/views/test_step_sets/new.html.slim
= link_to t('shared.back_link', target: SharedTestStepSet.model_name.human(count: 2)), test_step_sets_path

h1
  small.glyphicon.glyphicon-share
  = " #{t('.title')}"

= simple_form_for @base_test_step_set, url: test_step_sets_path, method: :post, as: :test_step_set do |f|
  = hidden_field_tag :base_test_step_set_id, @base_test_step_set&.to_param if @base_test_step_set.present?
  = f.error_notification
  = f.input :title
  = f.input :description, hint: t('shared.markdown_support_hint', link: link_to(t('shared.what_is_markdown'), doc_url(:markdown), target: '_blank')).html_safe
  = render 'shared/test_steps_fields', f: f
  = f.button :submit, class: 'btn-success'

app/views/test_step_sets/show.html.slim
- content_for :title, t('.title', test_step_set_title: @test_step_set.title).titleize

= link_to t('shared.back_link', target: SharedTestStepSet.model_name.human(count: 2)), test_step_sets_path

.block
  .pull-right
    .e2e-margined-btn-group
      - if policy(Test.new).new?
        = link_to t('shared.buttons.create_test'), new_test_path(base_test_step_set_id: @test_step_set), class: 'btn btn-success'
      - if policy(SharedTestStepSet.new).new?
        = link_to t('shared.buttons.fork'), new_test_step_set_path(base_test_step_set_id: @test_step_set), class: 'btn btn-default'
      - if policy(@test_step_set).edit?
        = link_to t('shared.buttons.edit'), edit_test_step_set_path(@test_step_set), class: 'btn btn-default'
      - if policy(@test_step_set).destroy?
        = link_to t('shared.buttons.delete'), test_step_set_path(@test_step_set), method: :delete, class: 'btn btn-default', data: {confirm: t('shared.confirm')}
  h1.e2e-truncate
    small.glyphicon.glyphicon-share
    = " #{@test_step_set.title}"

= render 'shared/test_step_set_panel', test_step_set: @test_step_set

.row
  .col-lg-6
    - user_shared_test_step_set = @test_step_set.user_shared_test_step_sets.with_user(current_user).build
    - if policy(user_shared_test_step_set).new?
      .panel.panel-default
        .panel-heading
          small.glyphicon.glyphicon-send
          = " #{t('.share_test_step_set')}"
        .panel-body
          = form_tag test_step_set_user_shared_test_step_sets_path(@test_step_set), method: :post, html: {autocomplete: 'off'} do
            .form-group
              = label_tag :email, User.human_attribute_name(:email).humanize
              = text_field_tag :email, nil, class: 'form-control', autocomplete: 'off'

            .form-group
              = submit_tag t("devise.invitations.new.submit_button"), class: 'btn btn-default'

  .col-lg-6
    - if @user_shared_test_step_sets.present?
      div.panel.panel-default
        div.panel-heading
          small.glyphicon.glyphicon-user
          = " #{t('.shared_users')}"
        table.table
          tr
            th = User.human_attribute_name(:name).humanize
          - @user_shared_test_step_sets.each do |ut|
            tr
              td
                = gravatar_image_tag(ut.user.email, alt: ut.user.name, gravatar: { size: 20 })
                |  
                = ut.user.name
      div.panel
        = link_to t('shared.more_records', target: UserSharedTestStepSet.model_name.human(count: 2)), test_step_set_user_shared_test_step_sets_path(@test_step_set)