config/routes.rb
Rails.application.routes.draw do
  if Settings.service.admin || Settings.service.sidekiq
    scope :admin do
      devise_for :admin_users, ActiveAdmin::Devise.config
    end
  end

  ActiveAdmin.routes(self) if Settings.service.admin

  authenticate :admin_user do
    if Settings.service.sidekiq
      require 'sidekiq/web'
      mount Sidekiq::Web => '/admin/sidekiq_web'
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    invitations: 'users/invitations'
  }

  resources :tests, shallow: true do
    resources :user_tests, only: [:create, :update, :index, :destroy]
    resources :test_versions, only: [] do
      resources :user_test_versions, only: [:create, :update, :index, :destroy]
    end
    resources :user_notification_settings, only: [:index], path: :notification_settings
  end
  resources :user_integrations, only: [:index] do
    collection do
      resources :slack_integrations, path: 'slack'
    end
    resources :user_notification_settings, only: [:index], path: :notification_settings
  end
  get 'user_integrations/:type/:id', to: -> { root_path }, as: :polymorphic_user_integration # Fake route for polymorphic routes
  resources :tests, only: [] do
    get 'versions' => 'test_versions#index', as: :test_versions
    get ':number' => 'test_versions#show', as: :test_version
    delete ':number' => 'test_versions#destroy'
    nested do
      scope ':number', as: :version do
        resources :test_executions, only: [:index, :create]
      end
    end
  end
  resources :test_executions, shallow: true, only: [:show] do
    member do
      get :done
    end
    resources :test_execution_shares, only: [:index, :create, :update, :destroy]
  end
  resources :test_step_executions, only: [:show]
  resources :user_credentials, only: [:index] do
    collection do
      resource :browserstack_credentials, only: [:create, :update, :destroy], path: :browserstack
    end
  end
  resources :test_step_sets, shallow: true do
    resources :user_shared_test_step_sets, only: [:index, :create, :destroy]
  end
  resources :user_api_tokens, path: 'api_tokens', only: [:index, :create, :update, :destroy]
  namespace :misc, path: '' do
    get :assigned_tests
    get :test_executions
  end
  resources :user_notification_settings, only: [:index, :create, :update], path: :notification_settings
  namespace :docs do
    get :api
  end

  namespace :api, constraints: { format: 'json' }, defaults: { format: 'json' } do
    namespace :v1 do
      resources :tests, only: [] do
        get 'versions' => 'test_versions#index', as: :test_versions
        get ':number' => 'test_versions#show', as: :test_version
        delete ':number' => 'test_versions#destroy'
        nested do
          scope ':number', as: :version do
            resources :test_executions, only: [:index, :create]
          end
        end
      end
      resources :test_executions, only: [:show]
      get :docs, to: 'docs#index'
    end
    namespace :graphql do
      resource :query, only: [:create, :show]
      resource :schema, only: [:show]
    end
    match '*path' => 'misc#not_found', via: :all
  end

  root to: 'misc#home'
end

app/models/browser_set.rb
class BrowserSet < ApplicationRecord
  has_many :browser_browser_sets, inverse_of: :browser_set
  has_many :browsers, through: :browser_browser_sets

  validates :name, length: { maximum: 255 }, presence: true
end

app/views/project_tests/_checkboxes.html.slim
- disabled ||= nil

- unless disabled
  div
    select#browser_sets_select.selectpicker
      option value="" Custom
      - browser_sets.each do |bs|
        option value=bs.id data-browser-ids=bs.browsers.map(&:id).map(&:to_s).to_json = bs.name

div
  div style="margin-bottom: 10px;"
    a#toggle_browsers href="#" Show all browsers
  div#all_browsers style='display: none;'
    - local_browsers = browsers.select { |b| b.is_a?(Browser::Local) }
    - if local_browsers.present?
      div.checkbox
        h3 Local
        - local_browsers.each do |browser|
          label
            = check_box_tag "#{f.object_name}[browser_ids][]", browser.id, false, disabled: disabled, checked: selected_browsers.include?(browser), data: { 'browser-checkbox': true }
            = browser.name
    - browserstack_browsers = browsers.select { |b| b.is_a?(Browser::Browserstack) }.group_by { |b| [b.os, b.os_version] }
    - if browserstack_browsers.present?
      div.checkbox
        h3 Browserstack
        - browserstack_browsers.each do |(os, os_version), browsers|
          h4 = "#{os} #{os_version}"
          - browsers.each do |browser|
            label
              = check_box_tag "#{f.object_name}[browser_ids][]", browser.id, false, disabled: disabled, checked: selected_browsers.include?(browser), data: { 'browser-checkbox': true }
              = browser.name

app/views/project_tests/index.html.slim
= link_to 'Back to project', project_path(@project)
h1 Tests

- if @tests.present?
  div.panel.panel-default
    table.table
      tr
        th ID
        th Parent
        th Title
        th Created At
        th Created By
      - @tests.each do |t|
        tr
          td = link_to t.id, test_path(t)
          td = link_to t.test_step_set_id, polymorphic_test_step_set_path(t.base_test_step_set) if t.base_test_step_set.present? && policy(t.base_test_step_set).show?
          td = link_to t.title, test_path(t) if t.title.present?
          td = link_to t.created_at.to_s, test_path(t)
          td = t.user.name_or_email
    = paginate @tests