config/routes.rb
Rails.application.routes.draw do
  if Settings.service.admin || Settings.service.sidekiq
    scope :admin do
      devise_for :admin_users, ActiveAdmin::Devise.config
    end
  end

  ActiveAdmin.routes(self) if Settings.service.admin

  authenticate :admin_user do
    if Settings.service.sidekiq
      require 'sidekiq/web'
      mount Sidekiq::Web => '/admin/sidekiq_web'
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    invitations: 'users/invitations'
  }

  resources :tests, shallow: true do
    resources :user_tests, only: [:create, :update, :index, :destroy]
    resources :test_versions, only: [] do
      resources :user_test_versions, only: [:create, :update, :index, :destroy]
    end
    resources :user_notification_settings, only: [:index], path: :notification_settings
  end
  resources :user_integrations, only: [:index] do
    collection do
      resources :slack_integrations, path: 'slack'
    end
    resources :user_notification_settings, only: [:index], path: :notification_settings
  end
  get 'user_integrations/:type/:id', to: -> { root_path }, as: :polymorphic_user_integration # Fake route for polymorphic routes
  resources :tests, only: [] do
    get 'versions' => 'test_versions#index', as: :test_versions
    get ':number' => 'test_versions#show', as: :test_version
    delete ':number' => 'test_versions#destroy'
    nested do
      scope ':number', as: :version do
        resources :test_executions, only: [:index, :create]
      end
    end
  end
  resources :test_executions, shallow: true, only: [:show] do
    member do
      get :done
    end
    resources :test_execution_shares, only: [:index, :create, :update, :destroy]
  end
  resources :test_step_executions, only: [:show]
  resources :user_credentials, only: [:index] do
    collection do
      resource :browserstack_credentials, only: [:create, :update, :destroy], path: :browserstack
    end
  end
  resources :test_step_sets, shallow: true do
    resources :user_shared_test_step_sets, only: [:index, :create, :destroy]
  end
  resources :user_api_tokens, path: 'api_tokens', only: [:index, :create, :update, :destroy]
  namespace :misc, path: '' do
    get :assigned_tests
    get :test_executions
  end
  resources :user_notification_settings, only: [:index, :create, :update], path: :notification_settings
  namespace :docs do
    get :api
  end

  namespace :api, constraints: { format: 'json' }, defaults: { format: 'json' } do
    namespace :v1 do
      resources :tests, only: [] do
        get 'versions' => 'test_versions#index', as: :test_versions
        get ':number' => 'test_versions#show', as: :test_version
        delete ':number' => 'test_versions#destroy'
        nested do
          scope ':number', as: :version do
            resources :test_executions, only: [:index, :create]
          end
        end
      end
      resources :test_executions, only: [:show]
      get :docs, to: 'docs#index'
    end
    namespace :graphql do
      resource :query, only: [:create, :show]
      resource :schema, only: [:show]
    end
    match '*path' => 'misc#not_found', via: :all
  end

  root to: 'misc#home'
end

app/controllers/api/misc_controller.rb
module Api
  class MiscController < BaseController
    def not_found
      raise E2eTester::NotFound
    end
  end
end

app/controllers/misc_controller.rb
class MiscController < BaseController
  skip_after_action :verify_authorized
  after_action :verify_policy_scoped

  auto_decorate :user_test_versions

  def home
    @tests = policy_scope(current_user.accessible_tests).latest.limit(20)
    @user_test_versions = policy_scope(current_user.user_test_versions).eager_load(:test_version).latest.limit(20)
  end

  def assigned_tests
    @user_test_versions = policy_scope(current_user.user_test_versions).eager_load(:test_version).latest.page(params[:page]).per(20)
  end

  def test_executions
    @test_executions = policy_scope(current_user.test_executions).latest.page(params[:page]).per(20)
  end
end

app/views/misc/assigned_tests.html.slim
h1
  small.glyphicon.glyphicon-tasks
  = " #{t('.title')}"

- if @user_test_versions.present?
  .panel.panel-default
    table.table.table-striped
      tr
        th = Test.human_attribute_name(:title).humanize
        th = UserTestVersion.human_attribute_name(:assigned_at).humanize
        th = UserTestVersion.human_attribute_name(:assigned_by).humanize
        th
      - @user_test_versions.each do |utv|
        tr
          td = link_to utv.test_version.title, test_version_position_path(utv.test_version)
          td = link_to test_version_position_path(utv.test_version) do
            time datetime=utv.created_at.iso8601 data-timeago='' = utv.created_at.to_s
          td
            = gravatar_image_tag(utv.assigned_by.email, alt: utv.assigned_by.name, gravatar: { size: 20 })
            |  
            = utv.assigned_by.name
          td
            = button_to t('shared.buttons.execute'), test_version_position_test_executions_path(utv.test_version), class: 'btn btn-xs btn-primary', method: :post
  .center-block.text-center
    = paginate @user_test_versions
- else
  .alert.alert-warning
    = t('shared.no_records', target: Test.model_name.human)

app/views/misc/home.html.slim
h1
  small.glyphicon.glyphicon-briefcase
  = " #{t('.your_tests')}"

- if @tests.present?
  .panel.panel-default
    table.table.table-striped
      tr
        th = Test.human_attribute_name(:title).humanize
      - @tests.each do |t|
        tr
          td = link_to t.title, test_path(t)
  = link_to t('shared.all_records', target: Test.model_name.human(count: 2)), tests_path
-else
  .alert.alert-warning
    = t('shared.no_records', target: Test.model_name.human)

h1
  small.glyphicon.glyphicon-tasks
  = " #{t('.assigned_tests')}"

- if @user_test_versions.present?
  .panel.panel-default
    table.table.table-striped
      tr
        th = Test.human_attribute_name(:title).humanize
        th = UserTest.human_attribute_name(:assigned_at).humanize
        th = UserTest.human_attribute_name(:assigned_by).humanize
      - @user_test_versions.each do |utv|
        tr
          td = link_to utv.test_version.title, test_version_position_path(utv.test_version)
          td = link_to test_version_position_path(utv.test_version) do
            time datetime=utv.created_at.iso8601 data-timeago='' = utv.created_at.to_s
          td
            = gravatar_image_tag(utv.assigned_by.email, alt: utv.assigned_by.name, gravatar: { size: 20 })
            |  
            = utv.assigned_by.name
  = link_to t('shared.all_records', target: Test.model_name.human(count: 2)), misc_assigned_tests_path
-else
  .alert.alert-warning
    = t('shared.no_records', target: Test.model_name.human)

app/views/misc/root.html.slim
ul
  - if user_signed_in?
    li = link_to "Projects", projects_path
    li = link_to "Tests", tests_path
    li = link_to "Test Step Sets", test_step_sets_path
    li = link_to "Invite User", new_user_invitation_path
  - else
    li = link_to "Sign In", new_user_session_path

app/views/misc/test_executions.html.slim
h1
  small.glyphicon.glyphicon-film
  = " #{t('.title')}"

- if @test_executions.present?
  .panel.panel-default
    table.table.table-striped
      tr
        th = Test.human_attribute_name(:title).humanize
        th = TestExecution.human_attribute_name(:state).humanize
        th = TestExecution.human_attribute_name(:executed_at).humanize
        th
      - @test_executions.each do |te|
        tr
          td = link_to te.test_version.title, test_execution_path(te)
          td = bootstrap_status_tag :span, te.state_i18n, te.done?, te.failed?
          td = link_to test_execution_path(te) do
            time datetime=te.created_at.iso8601 data-timeago='' = te.created_at.to_s
          td
            = link_to t('shared.buttons.retry'), test_version_position_test_executions_path(te.test_version), class: 'btn btn-xs btn-primary', method: :post

  .center-block.text-center
    = paginate @test_executions
- else
  .alert.alert-warning
    = t('shared.no_records', target: TestExecution.model_name.human)